CREATE DATABASE IF NOT EXISTS lablocator;
USE lablocator;

CREATE TABLE IF NOT EXISTS student (
    stuID INT AUTO_INCREMENT PRIMARY KEY,
    stuFName VARCHAR(50) NOT NULL,
    stuLName VARCHAR(50) NOT NULL,
    stuCourse VARCHAR(50) NOT NULL,
    stuYear INT NOT NULL
);

CREATE TABLE IF NOT EXISTS workstation (
    wsID INT AUTO_INCREMENT PRIMARY KEY,
    wsLabRoom VARCHAR(50) NOT NULL,
    wsPCNum VARCHAR(50) NOT NULL,
    wsSoftware VARCHAR(255),
    wsStatus VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS booking (
    bookID INT AUTO_INCREMENT PRIMARY KEY,
    stuID INT NOT NULL,
    wsID INT NOT NULL,
    bookStart DATETIME NOT NULL,
    bookEnd DATETIME NOT NULL,
    purpose TEXT,
    FOREIGN KEY (stuID) REFERENCES student(stuID) ON DELETE CASCADE,
    FOREIGN KEY (wsID)  REFERENCES workstation(wsID) ON DELETE CASCADE
);