CREATE DATABASE IF NOT EXISTS program_event;
USE program_event;

CREATE TABLE IF NOT EXISTS participant (
    partID INT AUTO_INCREMENT PRIMARY KEY,
    partFName VARCHAR(50) NOT NULL,
    partLName VARCHAR(50) NOT NULL,
    partFullName VARCHAR(100) NOT NULL,
    partCourse VARCHAR(50) NOT NULL,
    partYearLevel INT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    evCode VARCHAR(50) PRIMARY KEY,
    evName VARCHAR(100) NOT NULL,
    evDate DATE NOT NULL,
    evVenue VARCHAR(100) NOT NULL,
    evFee DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS booking (
    regCode INT AUTO_INCREMENT PRIMARY KEY,
    partID INT NOT NULL,
    evCode VARCHAR(50) NOT NULL,
    regDate DATE NOT NULL,
    regMode VARCHAR(50) NOT NULL,
    FOREIGN KEY (partID) REFERENCES participant(partID) ON DELETE CASCADE,
    FOREIGN KEY (evCode) REFERENCES events(evCode) ON DELETE CASCADE
);


